### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/gtfstools#26]
I finally started playing with this package again. Here is a checklist of what I consider important prior to submitting v1.0.0 to CRAN.

- [x] implement `filter_trip_id()` tests
- [x] adjust `filter_route_id()` implementation and documentation to match `filter_trip_id()`'s
- [x] make `filter_route_type()` depend on `filter_route_id()` (probably joining them in a single file)
- [x] review and merge #22
- [x] start depending on `{gtfsio}` on `read_gtfs()` and `write_gtfs()`
- [x] add `filter_shape_id()`
- [x] add `filter_stop_id()`
- [x] use the two above to implement `crop_gtfs()`
- [x] start using `cpp_time_to_seconds()`
- [x] expand filtering functions to include transfers, pathways and levels tables
- [x] write filtering vignette 
- [x] start depending on gtfsio v1.0.0
- [x] adjust calls to gtfsio's checking/asserting functions
- [x] stop raising error in `conver_shapes/stops_to_sf()` if none of the ids exist. return empty sf instead

It'll be important to write a vignette about the filtering functions as well, but that could be left out to v0.2.1, perhaps.

I might add some checks to this issue as I see fit.
